### PR TITLE
Remove "always yes" option from "dnf remove" command

### PR DESCRIPTION
**Pull request by siepkes**
It's probably best to let DNF prompt the user what is going to be removed instead of telling the user to pass the `-y` flag.

To my knowledge I have a fairly standard Fedora 35 install however DNF came to the conclusion it needed to remove a whole slew of packages which it deemed "unused dependencies":

```
Removing:
 zfs-fuse                                                               x86_64                             0.7.2.2-20.fc35                                              @fedora                              6.0 M
Removing dependent packages:
 gnome-boxes                                                            x86_64                             41.1-1.fc35                                                  @fedora                              6.1 M
 libvirt                                                                x86_64                             7.6.0-3.fc35                                                 @fedora                                0  
 libvirt-daemon-kvm                                                     x86_64                             7.6.0-3.fc35                                                 @fedora                                0  
 vagrant-libvirt                                                        noarch                             0.4.1-3.fc35                                                 @fedora                              229 k
Removing unused dependencies:
 SDL2_image                                                             x86_64                             2.0.5-7.fc35                                                 @fedora                              168 k
 corosynclib                                                            x86_64                             3.1.6-1.fc35                                                 @updates                             157 k
 glusterfs                                                              x86_64                             9.4-1.fc35                                                   @updates                             2.8 M
 glusterfs-cli                                                          x86_64                             9.4-1.fc35                                                   @updates                             493 k
 glusterfs-client-xlators                                               x86_64                             9.4-1.fc35                                                   @updates                             3.8 M
 glusterfs-fuse                                                         x86_64                             9.4-1.fc35                                                   @updates                             563 k
 gvncpulse                                                              x86_64                             1.3.0-1.fc35                                                 @updates                              47 k
 libgfapi0                                                              x86_64                             9.4-1.fc35                                                   @updates                             227 k
 libglusterd0                                                           x86_64                             9.4-1.fc35                                                   @updates                              15 k
 libiscsi                                                               x86_64                             1.19.0-4.fc35                                                @fedora                              223 k
 libnfs                                                                 x86_64                             4.0.0-5.fc35                                                 @fedora                              435 k
 libqb                                                                  x86_64                             2.0.4-1.fc35                                                 @updates                             212 k
 librados2                                                              x86_64                             2:16.2.7-2.fc35                                              @updates                              13 M
 librbd1                                                                x86_64                             2:16.2.7-2.fc35                                              @updates                              15 M
 libvirt-client                                                         x86_64                             7.6.0-3.fc35                                                 @fedora                              899 k
 libvirt-daemon-config-nwfilter                                         x86_64                             7.6.0-3.fc35                                                 @fedora                               20 k
 libvirt-daemon-driver-interface                                        x86_64                             7.6.0-3.fc35                                                 @fedora                              593 k
 libvirt-daemon-driver-libxl                                            x86_64                             7.6.0-3.fc35                                                 @fedora                              875 k
 libvirt-daemon-driver-lxc                                              x86_64                             7.6.0-3.fc35                                                 @fedora                              964 k
 libvirt-daemon-driver-nodedev                                          x86_64                             7.6.0-3.fc35                                                 @fedora                              650 k
 libvirt-daemon-driver-nwfilter                                         x86_64                             7.6.0-3.fc35                                                 @fedora                              683 k
 libvirt-daemon-driver-storage                                          x86_64                             7.6.0-3.fc35                                                 @fedora                                0  
 libvirt-daemon-driver-storage-disk                                     x86_64                             7.6.0-3.fc35                                                 @fedora                               32 k
 libvirt-daemon-driver-storage-gluster                                  x86_64                             7.6.0-3.fc35                                                 @fedora                               40 k
 libvirt-daemon-driver-storage-iscsi                                    x86_64                             7.6.0-3.fc35                                                 @fedora                               24 k
 libvirt-daemon-driver-storage-iscsi-direct                             x86_64                             7.6.0-3.fc35                                                 @fedora                               32 k
 libvirt-daemon-driver-storage-logical                                  x86_64                             7.6.0-3.fc35                                                 @fedora                               32 k
 libvirt-daemon-driver-storage-mpath                                    x86_64                             7.6.0-3.fc35                                                 @fedora                               16 k
 libvirt-daemon-driver-storage-rbd                                      x86_64                             7.6.0-3.fc35                                                 @fedora                               44 k
 libvirt-daemon-driver-storage-scsi                                     x86_64                             7.6.0-3.fc35                                                 @fedora                               24 k
 libvirt-daemon-driver-storage-sheepdog                                 x86_64                             7.6.0-3.fc35                                                 @fedora                               20 k
 libvirt-daemon-driver-storage-zfs                                      x86_64                             7.6.0-3.fc35                                                 @fedora                               24 k
 libvirt-daemon-driver-vbox                                             x86_64                             7.6.0-3.fc35                                                 @fedora                              839 k
 libvirt-gconfig                                                        x86_64                             4.0.0-3.fc35                                                 @fedora                              393 k
 libvirt-gobject                                                        x86_64                             4.0.0-3.fc35                                                 @fedora                              240 k
 lttng-ust                                                              x86_64                             2.12.2-5.fc35                                                @fedora                              1.1 M
 qemu-audio-alsa                                                        x86_64                             2:6.1.0-10.fc35                                              @updates                              29 k
 qemu-audio-jack                                                        x86_64                             2:6.1.0-10.fc35                                              @updates                              24 k
 qemu-audio-oss                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              20 k
 qemu-audio-pa                                                          x86_64                             2:6.1.0-10.fc35                                              @updates                              28 k
 qemu-audio-sdl                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              20 k
 qemu-audio-spice                                                       x86_64                             2:6.1.0-10.fc35                                              @updates                              20 k
 qemu-block-curl                                                        x86_64                             2:6.1.0-10.fc35                                              @updates                              37 k
 qemu-block-dmg                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              16 k
 qemu-block-gluster                                                     x86_64                             2:6.1.0-10.fc35                                              @updates                              41 k
 qemu-block-iscsi                                                       x86_64                             2:6.1.0-10.fc35                                              @updates                              51 k
 qemu-block-nfs                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              33 k
 qemu-block-rbd                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              42 k
 qemu-block-ssh                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              39 k
 qemu-char-baum                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              20 k
 qemu-char-spice                                                        x86_64                             2:6.1.0-10.fc35                                              @updates                              21 k
 qemu-device-display-qxl                                                x86_64                             2:6.1.0-10.fc35                                              @updates                              92 k
 qemu-device-display-vhost-user-gpu                                     x86_64                             2:6.1.0-10.fc35                                              @updates                             255 k
 qemu-device-display-virtio-gpu                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              65 k
 qemu-device-display-virtio-gpu-gl                                      x86_64                             2:6.1.0-10.fc35                                              @updates                              38 k
 qemu-device-display-virtio-gpu-pci                                     x86_64                             2:6.1.0-10.fc35                                              @updates                              16 k
 qemu-device-display-virtio-gpu-pci-gl                                  x86_64                             2:6.1.0-10.fc35                                              @updates                              16 k
 qemu-device-display-virtio-vga                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              17 k
 qemu-device-display-virtio-vga-gl                                      x86_64                             2:6.1.0-10.fc35                                              @updates                              15 k
 qemu-device-usb-host                                                   x86_64                             2:6.1.0-10.fc35                                              @updates                              51 k
 qemu-device-usb-redirect                                               x86_64                             2:6.1.0-10.fc35                                              @updates                              70 k
 qemu-device-usb-smartcard                                              x86_64                             2:6.1.0-10.fc35                                              @updates                              34 k
 qemu-kvm                                                               x86_64                             2:6.1.0-10.fc35                                              @updates                               0  
 qemu-system-x86                                                        x86_64                             2:6.1.0-10.fc35                                              @updates                               0  
 qemu-ui-curses                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              48 k
 qemu-ui-egl-headless                                                   x86_64                             2:6.1.0-10.fc35                                              @updates                              16 k
 qemu-ui-gtk                                                            x86_64                             2:6.1.0-10.fc35                                              @updates                              79 k
 qemu-ui-opengl                                                         x86_64                             2:6.1.0-10.fc35                                              @updates                              33 k
 qemu-ui-sdl                                                            x86_64                             2:6.1.0-10.fc35                                              @updates                              45 k
 qemu-ui-spice-app                                                      x86_64                             2:6.1.0-10.fc35                                              @updates                              16 k
 qemu-ui-spice-core                                                     x86_64                             2:6.1.0-10.fc35                                              @updates                              69 k
 rubygem-builder                                                        noarch                             3.2.4-5.fc35                                                 @fedora                               32 k
 rubygem-excon                                                          noarch                             0.79.0-1.fc35                                                @fedora                               98 k
 rubygem-fog-core                                                       noarch                             2.2.4-2.fc35                                                 @fedora                              118 k
 rubygem-fog-json                                                       noarch                             1.2.0-7.fc35                                                 @fedora                              3.9 k
 rubygem-fog-libvirt                                                    noarch                             0.8.0-2.fc35                                                 @fedora                               73 k
 rubygem-fog-xml                                                        noarch                             0.1.3-7.fc35                                                 @fedora                              8.3 k
 rubygem-formatador                                                     noarch                             0.2.5-12.fc35                                                @fedora                              9.9 k
 rubygem-multi_json                                                     noarch                             1.15.0-3.fc35                                                @fedora                               33 k
 rubygem-nokogiri                                                       x86_64                             1.12.5-1.fc35                                                @updates                             1.0 M
 rubygem-racc                                                           x86_64                             1.6.0-200.fc35                                               @updates                             185 k
 rubygem-rexml                                                          noarch                             3.2.5-151.fc35                                               @fedora                              399 k
 rubygem-ruby-libvirt                                                   x86_64                             0.7.1-13.fc35                                                @fedora                              288 k
 sheepdog                                                               x86_64                             1.0.1-16.fc35                                                @fedora                              732 k
 spice-server                                                           x86_64                             0.15.0-2.fc35                                                @fedora                              1.1 M
 virglrenderer                                                          x86_64                             0.9.1-2.20210420git36391559.fc35                             @fedora                              462 k

```

### CODE REVIEW

**Comment by ne9z** [comment]
Yes, this is a valid concern. Please merge.

@gmelikov

**Comment by ne9z** [comment]
Maybe we should use `rpm` command to remove `zfs-fuse` package without removing dependencies.

**Comment by ne9z** [comment]
Apologies for the problem caused, but if your Fedora 35 setup is still available, the following command can remove `zfs-fuse` package alone:

```
rpm -e --nodeps zfs-fuse
```

**Review by gmelikov — APPROVED** [review]

**Comment by gmelikov** [comment]
Superseded by #246

**Pull request closed without merging**
