### PR TITLE
Use an environment variable for username in step 6.6

### PR DESCRIPTION
**Pull request by scott-ainsworth**
In step 6.6, Create a user account, use an environment variable for the user name to reduce the possibility of typos and simplify using copy-and-paste to run commands.

Signed-off-by: Scott G. Ainsworth <scott@ainsworth.us>

### CODE REVIEW

**Comment by scott-ainsworth** [comment]
If you would like me to create a new branch and consolidate the three commits into one, please let me know.

**Comment by rlaager** [comment]
> If you would like me to create a new branch and consolidate the three commits into one, please let me know.

It doesn't need to be a new branch, but ideally you would squash these commits into one. You can do that with something like `git rebase -i origin/master`, leave the first marked as "pick", and mark the others as "squash" (or "s") to squash them into the one above. This will give you an editor to change the commit message. In this case, you would be discarding the subsequent commit messages anyway, so instead of "squash" you can use "fixup" (or "f") in the rebase. Then do a _force_ push, e.g.: `git push -f`

If that rebasing/squashing is too confusing for you and you'd rather not, I can do it as part of accepting this PR if you'd prefer.

**Comment by scott-ainsworth** [comment]
Rebase/squash is old hat. Just wanted to check since not everyone likes it.  Just pushed the (hopefully) final version.

Thank you for your patience!

Scott

**Comment by rlaager** [comment]
I renamed it to $username, as that is what I would prefer. I applied the change to the other HOWTOs (Ubuntu 20.04 for Raspberry Pi and Debian Buster--I still haven't done a Bullseye one). Merged as 3c04e929a1ed86430a924485adda38fcfd5d776e.

Thanks!

**Pull request closed without merging**
