### PR TITLE
"efis" is an incorrect folder name

### PR DESCRIPTION
**Pull request by TheK0tYaRa**

### CODE REVIEW

**Comment by ne9z** [comment]
Hello, thanks for submitting this pull request.  We manage mirrored efi
system partitions under /boot/efis/ and mount one of them at the
canonical path /boot/efi, so that GRUB bootloader can correctly identify
it as a vfat-formatted partition.  So the document is correct and there
is no need for a fix.

**Comment by TheK0tYaRa** [comment]
Was that tested in current conditions?

**Comment by ne9z** [comment]
What do you mean by "current conditions"?

I'm running this setup on several computers, some with a multi-disk
setup and some not.  So far the mirrored efi system partitions work well
so that the computer still boots even one of the disks failed.

**Comment by TheK0tYaRa** [comment]
I meant on current 'unstable' branch of nixos

**Comment by TheK0tYaRa** [comment]
Got a chinese lad asking for help with the following photos:
image

image

**Comment by TheK0tYaRa** [comment]
I can link the telegram message if you wish to assist them personally.

**Comment by ne9z** [comment]
Thanks for the info.  I have identified the problem and submitted my own pull request now.  Let your friend install the system again with the fixes documented here https://github.com/openzfs/openzfs-docs/pull/384/files and report back issues, if any.

**Pull request closed without merging**
