### PR TITLE
Move `Performance tuning` and `Hardware` pages from openzfs wiki

### PR DESCRIPTION
**Pull request by gmelikov**
Pandoc raw mediawiki->rst conversions are in separate commits for ease of review.

I'll add redirection in wiki after this PR merged.

We may want to move this pages because there are contributors ready to update them (there are some inconsistencies in Perf tuning page on wiki, for ex. with Postgresql case).

### CODE REVIEW

**Comment by gmelikov** [comment]
@ryao as the main contributor of these pages you may want to review this PR, thank you!

@ahrens hope you're not against moving these pages here, I've got some folks who may contribute to them.

**Review by rlaager — COMMENTED** [review]
This looks good to me, with some notes:
1. nit: s/Open ZFS/OpenZFS/
2. The mention that only FreeBSD has TRIM support is out of date.
3. The note about Linux setting the noop schedule should be removed. That is either no longer done or is deprecated.

**Review by rlaager — APPROVED** [review]
LGTM

**Comment by ahrens** [comment]
I'm fine with moving these to github.  Thanks!

**Pull request merged**
