### PR TITLE
Arch Linux: describe ed25519 support

### PR DESCRIPTION
**Pull request by ejiek**
ed25519 support: https://github.com/mkj/dropbear/pull/91

### CODE REVIEW

**Comment by rlaager** [comment]
@ejiek Could you add a Signed-off-by to the commit, please?

@ne9z Is this support now available in Arch?

**Comment by ne9z** [comment]
@ejiek Have you tested this though? Last time I checked, mkinitcpio-dropbear hook complains a lot for not being able to read ed25519 _host key_ generated with `ssh-keygen -Am pem`. For now I would just stick with good ol' RSA 3072 keys.

**Comment by ejiek** [comment]
@ne9z @rlaager this setup works a fresh install of AL (as of 07.03.2021).

I've experienced no problems with `ed25519` key in `/etc/dropbear/root_key`.
As for host keys `dropbearconvert openssh dropbear /etc/ssh/ssh_host_ed25519_key dropbear_ed25519_host_key` has succesfully converted a host key, but it's not done by mkinitcpio-dropbear hook [yet](https://github.com/grazzolini/mkinitcpio-dropbear/pull/13).

**Comment by ne9z** [comment]
Thanks for testing this out. So it means that ed25519 still does not work with `mkinitcpio-dropbear` without manually converting the host key first.

Please add this instruction and note to the pull request.

**Comment by ejiek** [comment]
I'd argue that this PR was about `/etc/dropbear/root_key` not a host key.
But I think that it can be expanded to ed25519 support =]

**Comment by ne9z** [comment]
Latest commit looks good to me. However Arch guide has significantly changed since this notice was proposed. "This branch has conflicts that must be resolved"

Maybe rebase on the latest version?

**Comment by ejiek** [comment]
Done!

I'm not sure how correct it is in English but I've added two commas to make reading a bit easier.

Thanks for all the support during this PR!

**Comment by ne9z** [comment]
I've opened [a pull request](https://github.com/ejiek/openzfs-docs/pull/1) in your repo to address the issues.

**Review by ne9z — APPROVED** [review]

**Comment by ne9z** [comment]
@rlaager I think it's ready for merging.

**Pull request closed without merging**
