### PR TITLE
added note on how to fix issue #349

### PR DESCRIPTION
**Pull request by alb-i**
Added description on how to fix the issue #349.

### CODE REVIEW

**Comment by rlaager** [comment]
I thought -d was supposed to take a directory, not the device itself. Can you provide more information on what your disk setup is like?

**Comment by alb-i** [comment]
A quick look at ```man zpool-import``` tells us, that 
```
             -d dir|device
                     Uses device or searches for devices or files in dir.  The -d option can be specified multiple times.
```

My disk setup:
```
lrwxrwxrwx 1 root root 13 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700800Y -> ../../nvme1n1
lrwxrwxrwx 1 root root 15 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700800Y-part1 -> ../../nvme1n1p1
lrwxrwxrwx 1 root root 13 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700808B -> ../../nvme0n1
lrwxrwxrwx 1 root root 15 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700808B-part2 -> ../../nvme0n1p2
lrwxrwxrwx 1 root root 15 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700808B-part3 -> ../../nvme0n1p3
lrwxrwxrwx 1 root root 15 Sep 20 07:52 nvme-Samsung_SSD_970_EVO_Plus_2TB_S4J4NJ0N700808B-part4 -> ../../nvme0n1p4
```

where ```nvme0``` is setup as in the text, ```nvme1``` only has one zfs-partition that has been added to extend the ```rpool```.

**Comment by alb-i** [comment]
so, any updates regarding the PR? I'm going to close it due to inactivity soon.

**Comment by rlaager** [comment]
Merged with changes as 81b6c209e409ff053dd47cce73a01a29fd706721

**Comment by rlaager** [comment]
I missed your follow-up. Thanks for the suggestion. I wish I knew more about what was going on, but adding the note seems reasonable for now.

**Pull request closed without merging**
