### PR TITLE
Initial Debian bookworm Root on ZFS page

### PR DESCRIPTION
**Pull request by jim-perkins**
Initial Doc for Debian 12 Bookworm root on ZFS.  Pretty much what was discussed with a few other things noticed when I verified the page.  Let me kow if there is anything else needed.  thanks so much for the existing documentation.

#442 
@rlaager

### CODE REVIEW

**Comment by rlaager** [comment]
Sorry for the delay. I do plan to look at this soon.

**Comment by caius** [comment]
Followed this through on physical hardware using UEFI booting and it worked fine for me :+1: Thanks for prepping the writeup @jim-perkins

**Comment by iamsilvio** [comment]
Was about to write this article by myself, thanks for your work!

if I run `gsettings set org.gnome.desktop.media-handling automount false` 
i get 
`-bash: gsettings: command not found`

using `https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-12.1.0-amd64-cinnamon.iso`

maybe this step is a litle dated

**Review by gmelikov — APPROVED** [review]
Diffed it with Dullseye's manual, it's nearly the same, so LGTM and i'm going to merge it as is. Thank you!

**Comment by gmelikov** [comment]
@rlaager I'll try to support Debian manual, feel free to ping me on problems.

**Pull request merged**
