### PR TITLE
Added Mailing list for FreeBSD

### PR DESCRIPTION
**Pull request by Spencer-Kinny**
Added mailing list for FreeBSD 

Fixes:
 #10845

### CODE REVIEW

**Comment by rlaager** [comment]
I assume you meant FreeBSD in the title, not OpenBSD, so I fixed that.

**Comment by Ornias1993** [comment]
@rlaager This is one big bag of shit.

1. #10845 is about adding an OpenZFS discuss mailinglist not a FreeBSD mailinglist
2. #10845 is about adding a mailinglist, not just a reference to one (meaning Brian or Matt need to add one)
3. He is not adding a FreeBSD mailinglist at all
4. The whole mess of urls

TLDR:
Even if the urls would be right it wouldn't be a FreeBSD mailinglist and there wouldn't be an OpenZFS Discuss mailinglist to begin with, thats why I filed #10845 in the first place.

I suggest closing this, it's a waste of time.

**Comment by gmelikov** [comment]
Let's discuss it first in https://github.com/openzfs/zfs/issues/10845 , link to ZoL mailing list as specially dedicated for FreeBSD doesn't look right for me too.

**Comment by Ornias1993** [comment]
@gmelikov My post wasn't about being disruptive, it was about trying to explain there was no relation between:
1. The title of the PR
2. The content of the PR (even the urls didn't match)
3. The referenced issue.

I called it a "bag of poop" to highlight the fact it isn't even clear what this PR is... It's a bag of random mismatch of linked issue, urls, titels and description.

**Comment by ahrens** [comment]
@Ornias1993 Let's continue this discussion offline, I sent you an email.

**Comment by Ornias1993** [comment]
@ahrens I think everything about this PR is said though...
But I'm always available by email as you know :)

**Pull request closed without merging**
